<h1>About</h1>
<p><span>倉儲:</span><a href="https://github.com/40823245/cad2020">https://github.com/40823245/cad2020</a></p>
<p></p>
<p><img alt="" height="120" src="/images/37855635_p0.jpg" width="200"/></p>
<h1>Work</h1>
<h4>放上每周作業並更新、自評互評、小組作業</h4>
<h2>w1</h2>
<h4>零件繪圖、建立網站、使用ssh</h4>
<h3>HW1</h3>
<h4><span>pdf1:Solidworks2017使用1mm繪製</span></h4>
<h4><span>pdf2:</span><span>Solidworks2017繪製(mm)</span></h4>
<p><iframe height="800" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vTLeLvshsO42EE6wLyhjojDlbksyiQjq_HgNn_dXbAvl4gxSz8F5jZ1Jm7CPwn8RjwH-dlzB3YIJb7_/pubhtml?gid=0&amp;single=true" width="500"></iframe></p>
<h4>OnShape</h4>
<h4>pdf1:OnShape使用1inch繪製</h4>
<p><iframe height="500" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vT--zaFsPh8jx9t_u1GuXfDO-ozEf-Rx9mpnT0OLBkHFE4S93rzdCXHfRT7Mtmo2QX8uGTIqJSos9sA/pubhtml?widget=true&amp;headers=false" width="300"></iframe></p>
<h4>pdf1</h4>
<h5>1-10</h5>
<p><img alt="" height="250" src="/images/1-10 .gif" width="300"/></p>
<h5>11-20</h5>
<p><img alt="" height="250" src="/images/11-20.gif" width="300"/></p>
<h5>21-30</h5>
<p><img alt="" height="250" src="/images/21-30.gif" width="300"/></p>
<h5>31-40</h5>
<p><img alt="" height="250" src="/images/31-40.gif" width="300"/></p>
<h5>41-50</h5>
<p><img alt="" height="250" src="/images/41-50.gif" width="300"/></p>
<h4>pdf2</h4>
<h5>件1</h5>
<p><img alt="" height="250" src="/images/1.gif" width="300"/></p>
<p>件2</p>
<p><img alt="" height="250" src="/images/2.gif" width="300"/></p>
<p>件3-1</p>
<p><img alt="" height="250" src="/images/3-1~3-2.gif" width="300"/></p>
<p>件3-2</p>
<p><img alt="" height="250" src="/images/3-3~3-5.gif" width="300"/></p>
<p>件3-3</p>
<p><img alt="" height="250" src="/images/3-6~3-10.gif" width="300"/></p>
<p>件3-4</p>
<p><img alt="" height="250" src="/images/3-11~3-15.gif" width="300"/></p>
<p>件3-5</p>
<p><img alt="" height="250" src="/images/3-16~3-19.gif" width="300"/></p>
<p>3-22</p>
<p><img alt="" height="250" src="/images/3-22.png" width="300"/></p>
<p>4-7</p>
<p><img alt="" height="250" src="/images/4-7.png" width="300"/></p>
<p>5-5</p>
<p><img alt="" height="250" src="/images/5-5.png" width="300"/></p>
<p>5-7</p>
<p><img alt="" height="250" src="/images/5-7.png" width="300"/></p>
<p>5-10</p>
<p><img alt="" height="250" src="/images/5-10.png" width="300"/></p>
<p>5-15</p>
<p><img alt="" height="250" src="/images/5-15.png" width="300"/></p>
<h2>w2-w3</h2>
<h4>零件繪製、表格製作、下載nx可攜版</h4>
<p><a href="/downloads/nxopen_getting_started_v12.pdf">nxopen_getting_started_v12.pdf</a></p>
<h2>w4-w6</h2>
<h4>零件繪製(小組、個人)、下載課程使用程式、使用Zoomit、soildworks API</h4>
<h3>HW2</h3>
<h4><a href="/downloads/45.SLDPRT">零件45</a></h4>
<h4><span>Solidworks2017使用10mm繪製</span></h4>
<h4><span>製圖影片:</span></h4>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/b2Fcik_oN-Y" width="560"></iframe></p>
<p><img alt="" height="120" src="/images/件45.png" width="120"/><img alt="" height="120" src="/images/件45-1.png" width="120"/></p>
<h4>程式碼:</h4>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">import pythoncom
import win32com.client
import win32api
import os
 
os.system("taskkill /IM sldworks.exe /F")
os.system("taskkill /IM sldworks_fs.exe /F")
 
'''
About DispatchEx and Dispatch Methods:
https://stackoverflow.com/questions/18648933/using-pywin32-what-is-the-difference-between-dispatch-and-dispatchex
Source code:
http://pywin32.hg.sourceforge.net/hgweb/pywin32/pywin32/file/0db1b26904d5/com/win32com/src/PyIDispatch.cpp
Doc:
https://docs.microsoft.com/en-us/dotnet/standard/native-interop/com-callable-wrapper
 
IDispatch: Provides a mechanism for late binding to type.
IDispatchEx:
    Interface supplied by the runtime if the class implements IExpando. The IDispatchEx interface is an extension of the IDispatch interface that, unlike IDispatch, enables enumeration, addition, deletion, and case-sensitive calling of members.
'''
app = win32com.client.DispatchEx("SldWorks.Application")
#app=win32com.client.Dispatch("SldWorks.Application")
 
# define var to convert variables
def var(type, value):
    # type needs to be string
    # use builtin getattr() to return pythoncom.type
    pytype = getattr(pythoncom, type)
    return win32com.client.VARIANT(pytype, value)
 
# for two-type variable convert
# is there any three-type variant?
def var2(type1, type2, value):
    pytype1 = getattr(pythoncom, type1)
    pytype2 = getattr(pythoncom, type2)
    return win32com.client.VARIANT(pytype1|pytype2, value)
     
def part(app, fileName, sketchName, dimName, newDim, newFileName):
    arg1 = var("VT_I4", 1)
    # GetMassProperties( ((3, 1), (16387, 3)))
    #arg1 = win32com.client.VARIANT(pythoncom.VT_I4, 1)
    arg2 = var("VT_I4", -1)
 
    # 0. need the most important obj app
    #app=win32com.client.Dispatch("SldWorks.Application")
    # use relative directory to open part
    # 1. open part file, need the path of the part file (need the file name)
    #doc=app.OpenDoc(".\\block2.SLDPRT", 1)
    doc=app.OpenDoc(os.path.join(os.getcwd(), fileName), 1)
    # save part as binary stl
    # can we save part as ASCII stl as well?
    #doc.SaveAs2(".\\block2.stl", 0, True, False)
    # the parameter VARIANT list for SelectByID2
    # can we automate the VARIANT conversion?
    # 2. use the sketch to select the SKETCH (need the sketch name)
    #SelectByID2((8, 1), (8, 1), (5, 1), (5, 1), (5, 1), (11, 1), (3, 1), (9, 1), (3, 1))
    #arg3 = var("VT_BSTR", "Sketch1")
    arg3 = var("VT_BSTR", sketchName)
    arg4 = var("VT_BSTR", "SKETCH")
    arg5 = var("VT_R8", 0)
    arg6 = var("VT_R8", 0)
    arg7 = var("VT_R8", 0)
    arg8 = var("VT_BOOL", False)
    arg9 = var("VT_I4", 0)
    arg10 = var("VT_DISPATCH", None)
    arg11 = var("VT_I4", 0)
    # select Sketch1 first
    status = doc.Extension.SelectByID2(arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
    # select DIMENSION to to modify
    # 3. use the dimension name @ sketch name @ part file name
    # to select the DIMENSION to modify
    #arg12 = var("VT_BSTR", "Width@Sketch1@block2.SLDPRT")
    arg12 = var("VT_BSTR", dimName+"@"+sketchName+"@"+fileName)
    arg13 = var("VT_BSTR", "DIMENSION")
    status = doc.Extension.SelectByID2(arg12, arg13, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
    #Dim swDimension As SldWorks.Dimension
    # 4. to bring out the parameter to modify, need the dimension name and 
    # sketch name
    #swDimension = doc.Parameter("Width@Sketch1")
    swDimension = doc.Parameter(dimName+"@"+sketchName)
    # the dimension unit is in meter
    # 5. need the new value of the parameter
    #swDimension.SystemValue = 0.50
    swDimension.SystemValue = newDim
    # 6. do the final house keeping process, clear selection and rebuild the part
    sel = doc.ClearSelection2 
    sel = True
    status = doc.EditRebuild()
    arg31 = var("VT_I4", 1)
    arg32 = var2("VT_I4", "VT_BYREF", 3)
    # 7. get the volume of the new part
    volumn = doc.Extension.GetMassProperties(arg31, arg32)
    #print(volumn[3]*1E9, "mm*3")
    # 8. save the new part (need the new part file name)
    #doc.SaveAs2(".\\block3.SLDPRT", 0, True, False)
    doc.SaveAs2(os.path.join(os.getcwd(), "html/" + newFileName + ".SLDPRT"), 0, True, False)
    # save jpg of part
    doc.EditRebuild()
    arg33 = var("VT_BSTR", "Isometric")
    doc.ShowNamedView(arg33)
    doc.ViewZoomtofit2()
    doc.SaveAs3(os.path.join(os.getcwd(), "html/" + newFileName + ".jpg"), 0, 0)
    # mm*3
    return str(round(volumn[3]*1E9, 3)) + " mm*3"
html = "以下零件採SolidWorks 2017繪製:&lt;br /&gt;&lt;br /&gt;&lt;table border='1' cellpadding='5'&gt;&lt;tr&gt;&lt;th&gt;Number&lt;/th&gt;&lt;th&gt;Part&lt;/th&gt;&lt;th&gt;Jpg&lt;/th&gt;&lt;th&gt;Width&lt;/th&gt;&lt;th&gt;Volume&lt;/th&gt;&lt;/tr&gt;"
index = 0
for i in range(1, 11):
    dim = i*0.002
    blockVolume = part(app, "45_step.SLDPRT", "Sketch1", "Width", dim, "45_" + str(i))
    print("45_" + str(i) + ".SLDPRT, dim= " + str(round(dim, 3)) +", volume= " + blockVolume)
    index += 1
    newFileName = "45_" + str(i)
    html += '''&lt;tr&gt;
    &lt;td&gt;''' + str(index) +'''&lt;/td&gt;
    &lt;td&gt;&lt;a href="./../downloads/sw_macro/html/''' + newFileName + '''.SLDPRT"&gt;''' + newFileName + '''.SLDPRT&lt;/a&gt;&lt;/td&gt;
    &lt;td&gt;&lt;img width="300" src="./../downloads/sw_macro/html/''' + newFileName + '''.jpg"&gt;&lt;/img&gt;&lt;/td&gt;
    &lt;td&gt;''' + str(round(dim*1000, 2)) + ''' mm &lt;/td&gt;
    &lt;td&gt;''' + blockVolume + '''&lt;/td&gt;
    &lt;/tr&gt;
    '''
html += "&lt;/table&gt;"
# save part.html
with open("./html/part.html", "w", encoding="utf-8") as f:
     f.write(html)
      
'''
for assembly
        swModelDocExt.SelectByID2("", "EDGE", -0.439825991092107, 7.07350481263802E-02, 0.40982045578545, true, 2, null, 0);
        swModelDocExt.SelectByID2("", "EDGE", -0.219003008311574, 0.073085842475507, 0.549481823985616, true, 4, null, 0);
        swModelDocExt.SelectByID2("Part-3@AssemModel", "COMPONENT", 0, 0, 0, true, 1, null, 0);
        swFeature = (Feature)swFeatureManager.FeatureLinearPattern2(3, 40 / 1000, 0, 0, false, true, "NULL", "NULL", false);
        assemblyModel.ClearSelection2(true);
'''
os.system("taskkill /IM sldworks.exe /F")
os.system("taskkill /IM sldworks_fs.exe /F")
# now the SolidWorks is embedding</pre>
<p><br/><br/></p>
<h4>SWAPI(-10%)</h4>
<p>以下零件採 SolidWorks 2017繪製: <br/><br/></p>
<table border="1" cellpadding="5" style="width: 578px;">
<tbody>
<tr>
<th style="width: 54px;">Number</th>
<th style="width: 89px;">Part</th>
<th style="width: 214.77px;">Jpg</th>
<th style="width: 49.2301px;">Width</th>
<th style="width: 97px;">Volume</th>
</tr>
<tr>
<td style="width: 54px;">1</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_1.SLDPRT">45_1.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_1.jpg" width="300"/></td>
<td style="width: 49.2301px;">2.0 mm</td>
<td style="width: 97px;">33123.501 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">2</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_2.SLDPRT">45_2.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_2.jpg" width="300"/></td>
<td style="width: 49.2301px;">4.0 mm</td>
<td style="width: 97px;">34207.295 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">3</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_3.SLDPRT">45_3.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_3.jpg" width="300"/></td>
<td style="width: 49.2301px;">6.0 mm</td>
<td style="width: 97px;">35292.855 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">4</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_4.SLDPRT">45_4.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_4.jpg" width="300"/></td>
<td style="width: 49.2301px;">8.0 mm</td>
<td style="width: 97px;">36405.806 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">5</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_5.SLDPRT">45_5.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_5.jpg" width="300"/></td>
<td style="width: 49.2301px;">10.0 mm</td>
<td style="width: 97px;">37570.796 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">6</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_6.SLDPRT">45_6.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_6.jpg" width="300"/></td>
<td style="width: 49.2301px;">12.0 mm</td>
<td style="width: 97px;">38770.796 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">7</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_7.SLDPRT">45_7.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_7.jpg" width="300"/></td>
<td style="width: 49.2301px;">14.0 mm</td>
<td style="width: 97px;">39970.796 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">8</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_8.SLDPRT">45_8.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_8.jpg" width="300"/></td>
<td style="width: 49.2301px;">16.0 mm</td>
<td style="width: 97px;">41170.796 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">9</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_9.SLDPRT">45_9.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_9.jpg" width="300"/></td>
<td style="width: 49.2301px;">18.0 mm</td>
<td style="width: 97px;">42370.796 mm*3</td>
</tr>
<tr>
<td style="width: 54px;">10</td>
<td style="width: 89px;"><a href="/downloads/sw_macro/html/45_10.SLDPRT">45_10.SLDPRT</a></td>
<td style="width: 214.77px;"><img src="/downloads/sw_macro/html/45_10.jpg" width="300"/></td>
<td style="width: 49.2301px;">20.0 mm</td>
<td style="width: 97px;">43570.796 mm*3</td>
</tr>
</tbody>
</table>
<h4>SWAPI(-5%)</h4>
<p>以下零件採SolidWorks 2017繪製:<br/><br/></p>
<table border="1" cellpadding="5">
<tbody>
<tr>
<th>Number</th>
<th>Part</th>
<th>Jpg</th>
<th>Width</th>
<th>Volume</th>
</tr>
<tr>
<td>1</td>
<td><a href="/downloads/sw_macro/45(-5%25)/html/45_1.SLDPRT">45_1.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_1.jpg" width="300"/></td>
<td>2.5 mm</td>
<td>33395.937 mm*3</td>
</tr>
<tr>
<td>2</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_2.SLDPRT">45_2.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_2.jpg" width="300"/></td>
<td>5.0 mm</td>
<td>34748.159 mm*3</td>
</tr>
<tr>
<td>3</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_3.SLDPRT">45_3.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_3.jpg" width="300"/></td>
<td>7.5 mm</td>
<td>36123.686 mm*3</td>
</tr>
<tr>
<td>4</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_4.SLDPRT">45_4.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_4.jpg" width="300"/></td>
<td>10.0 mm</td>
<td>37570.796 mm*3</td>
</tr>
<tr>
<td>5</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_5.SLDPRT">45_5.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_5.jpg" width="300"/></td>
<td>12.5 mm</td>
<td>39070.796 mm*3</td>
</tr>
<tr>
<td>6</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_6.SLDPRT">45_6.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_6.jpg" width="300"/></td>
<td>15.0 mm</td>
<td>40570.796 mm*3</td>
</tr>
<tr>
<td>7</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_7.SLDPRT">45_7.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_7.jpg" width="300"/></td>
<td>17.5 mm</td>
<td>42070.796 mm*3</td>
</tr>
<tr>
<td>8</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_8.SLDPRT">45_8.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_8.jpg" width="300"/></td>
<td>20.0 mm</td>
<td>43570.796 mm*3</td>
</tr>
<tr>
<td>9</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_9.SLDPRT">45_9.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_9.jpg" width="300"/></td>
<td>22.5 mm</td>
<td>45070.796 mm*3</td>
</tr>
<tr>
<td>10</td>
<td><a href="/downloads/sw_macro/45(-5%)/html/45_10.SLDPRT">45_10.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(-5%25)/html/45_10.jpg" width="300"/></td>
<td>25.0 mm</td>
<td>46570.796 mm*3</td>
</tr>
</tbody>
</table>
<h4>SWAPI(+10%)</h4>
<p>以下零件採SolidWorks 2017繪製: <br/><br/></p>
<table border="1" cellpadding="5">
<tbody>
<tr>
<th>Number</th>
<th>Part</th>
<th>Jpg</th>
<th>Width</th>
<th>Volume</th>
</tr>
<tr>
<td>1</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_1.SLDPRT">45_1.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_1.jpg" width="300"/></td>
<td>20.0 mm</td>
<td>43570.796 mm*3</td>
</tr>
<tr>
<td>2</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_2.SLDPRT">45_2.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_2.jpg" width="300"/></td>
<td>40.0 mm</td>
<td>54808.246 mm*3</td>
</tr>
<tr>
<td>3</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_3.SLDPRT">45_3.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_3.jpg" width="300"/></td>
<td>60.0 mm</td>
<td>67141.593 mm*3</td>
</tr>
<tr>
<td>4</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_4.SLDPRT">45_4.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_4.jpg" width="300"/></td>
<td>80.0 mm</td>
<td>79141.593 mm*3</td>
</tr>
<tr>
<td>5</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_5.SLDPRT">45_5.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_5.jpg" width="300"/></td>
<td>100.0 mm</td>
<td>91141.593 mm*3</td>
</tr>
<tr>
<td>6</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_6.SLDPRT">45_6.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_6.jpg" width="300"/></td>
<td>120.0 mm</td>
<td>103141.593 mm*3</td>
</tr>
<tr>
<td>7</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_7.SLDPRT">45_7.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_7.jpg" width="300"/></td>
<td>140.0 mm</td>
<td>115141.593 mm*3</td>
</tr>
<tr>
<td>8</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_8.SLDPRT">45_8.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_8.jpg" width="300"/></td>
<td>160.0 mm</td>
<td>127141.593 mm*3</td>
</tr>
<tr>
<td>9</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_9.SLDPRT">45_9.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_9.jpg" width="300"/></td>
<td>180.0 mm</td>
<td>139141.593 mm*3</td>
</tr>
<tr>
<td>10</td>
<td><a href="/downloads/sw_macro/45(+10%25)/html/45_10.SLDPRT">45_10.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+10%25)/html/45_10.jpg" width="300"/></td>
<td>200.0 mm</td>
<td>151141.593 mm*3</td>
</tr>
</tbody>
</table>
<h4>SWAPI(+5%)</h4>
<p>以下零件採SolidWorks 2017繪製: <br/><br/></p>
<table border="1" cellpadding="5">
<tbody>
<tr>
<th>Number</th>
<th>Part</th>
<th>Jpg</th>
<th>Width</th>
<th>Volume</th>
</tr>
<tr>
<td>1</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_1.SLDPRT">45_1.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_1.jpg" width="300"/></td>
<td>15.0 mm</td>
<td>40570.796 mm*3</td>
</tr>
<tr>
<td>2</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_2.SLDPRT">45_2.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_2.jpg" width="300"/></td>
<td>30.0 mm</td>
<td>49570.796 mm*3</td>
</tr>
<tr>
<td>3</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_3.SLDPRT">45_3.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_3.jpg" width="300"/></td>
<td>45.0 mm</td>
<td>58141.593 mm*3</td>
</tr>
<tr>
<td>4</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_4.SLDPRT">45_4.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_4.jpg" width="300"/></td>
<td>60.0 mm</td>
<td>67141.593 mm*3</td>
</tr>
<tr>
<td>5</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_5.SLDPRT">45_5.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_5.jpg" width="300"/></td>
<td>75.0 mm</td>
<td>76141.593 mm*3</td>
</tr>
<tr>
<td>6</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_6.SLDPRT">45_6.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_6.jpg" width="300"/></td>
<td>90.0 mm</td>
<td>85141.593 mm*3</td>
</tr>
<tr>
<td>7</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_7.SLDPRT">45_7.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_7.jpg" width="300"/></td>
<td>105.0 mm</td>
<td>94141.593 mm*3</td>
</tr>
<tr>
<td>8</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_8.SLDPRT">45_8.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_8.jpg" width="300"/></td>
<td>120.0 mm</td>
<td>103141.593 mm*3</td>
</tr>
<tr>
<td>9</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_9.SLDPRT">45_9.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_9.jpg" width="300"/></td>
<td>135.0 mm</td>
<td>112141.593 mm*3</td>
</tr>
<tr>
<td>10</td>
<td><a href="/downloads/sw_macro/45(+5%25)/html/45_10.SLDPRT">45_10.SLDPRT</a></td>
<td><img src="/downloads/sw_macro/45(+5%25)/html/45_10.jpg" width="300"/></td>
<td>150.0 mm</td>
<td>121141.593 mm*3</td>
</tr>
</tbody>
</table>
<h2>w7</h2>
<h4>下載並使用tcc、零件繪圖(小組、個人)、使用RoKiSim</h4>
<h3>tcc</h3>
<p>下載<a href="/downloads/tcc-0.9.27-win64-bin.zip">tcc資料夾</a>，並把tcc資料夾放在Y槽的跟目錄</p>
<p><img alt="" height="300" src="/images/tcc-8.png" width="500"/></p>
<h4>修改<span>start.bat裡的程式碼</span></h4>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">set path_portablegit=%Disk%:\Portablegit\bin;
set path_julia=%Disk%:\julia-1.5.2\bin;
set path_tcc=%Disk%:\tcc\;
 
path=%Disk%:;%path_python%;%path_portablegit%;%path_julia%;%path_tcc%;%path%;</pre>
<p><img alt="" height="300" src="/images/tcc-6.png" width="500"/></p>
<p>重新啟動start.bat</p>
<p>在黑窗輸入tcc，出現下圖代表成功</p>
<p><img alt="" height="300" src="/images/tcc-7.png" width="500"/></p>
<p>打開資料夾的<span>cpp.properties(移到白窗)</span></p>
<p><img alt="" height="300" src="/images/tcc-9.png" width="500"/></p>
<p>案view→Line Numbers</p>
<p><img alt="" height="300" src="/images/tcc-10.png" width="500"/></p>
<p>找到476行，並修改</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">ccopts=-pedantic -Os
#cc=g++ $(ccopts) -c $(FileNameExt) -o $(FileName).o
#ccc=gcc $(ccopts) -c $(FileNameExt) -o $(FileName).o
cc=y:/tcc/tcc.exe -run
ccc=y:/tcc/tcc.exe -run
 
make.command=make
command.compile.*.c=$(ccc) -std=c99
command.build.*.c=$(make.command)
command.build.*.h=$(make.command)
command.clean.*.c=$(make.command) clean
command.clean.*.h=$(make.command) clean
command.go.*.c=$(cc) $(FileNameExt)
#command.go.*.c=./$(FileName)
# To make the Go command both compile (if needed) and execute, use this setting:</pre>
<p><img alt="" height="300" src="/images/tcc-11.png" width="500"/></p>
<p>到tcc<span>→</span>examples<span>→text→c_ex→hello.c(移到白窗)並執行</span></p>
<p>測試1:</p>
<p><img alt="" height="500" src="/images/tcc-1.png" width="300"/></p>
<p>測試2:</p>
<p><img alt="" height="500" src="/images/tcc-3.png" width="300"/></p>
<h3>HW3</h3>
<h4>試用RoKiSim</h4>
<p><img alt="" height="538" src="/images/RoKiSim.gif" width="1000"/></p>
<h2>w8~w9</h2>
<h4>零件繪圖(小組、個人)、tcc轉換(.c→.py)、使用Pyslvs_UI、期中成績</h4>
<h3>tcc轉換</h3>
<h4>將.c檔轉換成.py檔，並執行py檔</h4>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">tcc -w -shared -DLIBTCC_AS_DLL -DONE_SOURCE multiply.c -o multiply.dll</pre>
<pre class="brush:py;auto-links:false;toolbar:false" contenteditable="false">tcc -w -shared -DLIBTCC_AS_DLL -DONE_SOURCE multiply_float.c -o multiply_float.dll</pre>
<p><img alt="" height="450" src="/images/tcc-4.png" width="500"/></p>
<p><img alt="" height="450" src="/images/tcc-5.png" width="500"/></p>
<h3>Pyslvs_UI</h3>
<h4>下載Pyslvs_UI並使用Pyslvs_UI畫連桿使其運作</h4>
<p><img alt="" height="350" src="/images/Pyslvs_UI.png" width="500"/></p>
<p><img alt="" height="600" src="/images/Pyslvs_UI.gif" width="600"/></p>
<h2>w10~w18</h2>
<h4>小組任務開始</h4>
<h4>小組倉儲:<a href="https://github.com/40823245/cad2020bg2">https://github.com/40823245/cad2020bg2</a></h4>
<h4>小組gitter:<a href="https://gitter.im/cad2020bg2/community">https://gitter.im/cad2020bg2/community</a></h4>
<h4>進度:</h4>
<h4>12/04</h4>
<h4>使用gitter進行討論，並錄製過程和截圖</h4>
<h4>12/11</h4>
<h4>討論並投票圖檔的版本</h4>
<h4>12/25</h4>
<h4>修改圖檔和模擬</h4>
<h4>01/07</h4>
<h4>程式模擬和做動模擬</h4>
<h4>01/15</h4>
<h4>程式模擬和修正之前的錯誤</h4>
<h3>12-04</h3>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/yx_p7bOd9Zc" width="560"></iframe></p>
<h4>討論結果為要做彈珠台，並小組分工</h4>
<h4>因為錄製影片出問題，所以後續內容用截圖</h4>
<p><img alt="" height="600" src="/images/1204-1.png" width="300"/></p>
<p><img alt="" height="600" src="/images/1204-2.png" width="300"/></p>
<p><img alt="" height="600" src="/images/1204-3.png" width="300"/></p>
<p><img alt="" height="600" src="/images/1204-4.png" width="300"/></p>
<p><img alt="" height="400" src="/images/1204-5.png" width="300"/></p>
<h3>12-11</h3>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/U-f1MEBiARo" width="560"></iframe> <iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/CUtr0AOiFDA" width="560"></iframe></p>
<h4>討論結果</h4>
<h4><a href="/downloads/彈珠台/彈珠檯完成品.ipt">圖檔</a></h4>
<p><img alt="" height="475" src="/images/1211.png" width="300"/></p>
<h3>12-24</h3>
<h4>測試影片:</h4>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/inBv_vKQhe0" width="560"></iframe></p>
<h4><a href="/downloads/彈珠台/pinblall-3.ttt">pinblall-3.ttt</a></h4>
<h4><a href="/downloads/彈珠台/組合彈珠檯.iam">圖檔</a></h4>
<h4>提出問題並修改</h4>
<p><img alt="" height="300" src="/images/1224.png" width="1000"/></p>
<h4>程式</h4>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">-- model in Solvespace 500 mm = 5000 mm in V-rep
--[[
Simulation is 10 times of realistic environment
floor in Solvespace 2.5 m x 2.5 m = 25 m x 25 m in V-rep
ball is in Solivespace 1g (0.001) = 0.01 kg in V-rep
hammer is in Solvespace 0.1 kg (100g) = 1kg in V-rep (0.1 for Inertia)
]]

threadFunction=function()
    while sim.getSimulationState()~=sim.simulation_advancing_abouttostop do
        -- Read the keyboard messages (make sure the focus is on the main window, scene view):
        message,auxiliaryData=sim.getSimulatorMessage()
        while message~=-1 do
            if (message==sim.message_keypress) then
                if (auxiliaryData[1]==2007) then
                    -- up key
                    velocity=-500
                    hammer_back = 0
                end
                if (auxiliaryData[1]==2008) then
                    -- down key
                     hammer_back = 1
                     velocity = 500
                end
            end
            message,auxiliaryData=sim.getSimulatorMessage()
        end
 
        -- We take care of setting the desired hammer position:
        if hammer_back == 1
            then sim.setObjectPosition(hammer,-1, position)
        end
        sim.setJointTargetVelocity(joint,velocity)
 
        -- Since this script is threaded, don't waste time here:
        sim.switchThread() -- Resume the script at next simulation loop start
    end
end
-- Put some initialization code here:
-- Retrieving of some handles and setting of some initial values:
joint=sim.getObjectHandle('joint')
hammer=sim.getObjectHandle('stick')
velocity=0
hammer_back=0
position=sim.getObjectPosition(hammer,-1)
 
-- Here we execute the regular thread code:
res,err=xpcall(threadFunction,function(err) return debug.traceback(err) end)
if not res then
    sim.addStatusbarMessage('Lua runtime error: '..err)
end
 
-- Put some clean-up code here:</pre>
<p></p>
<h3>01-07</h3>
<h4>程式模擬和做動模擬:</h4>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/zxhT-XWSy5c" width="560"></iframe></p>
<h4><a href="/downloads/彈珠台/pinblall-9.ttt">pinblall-9.ttt</a></h4>
<h4><a href="/downloads/彈珠台/彈珠台組合.stl">圖檔</a></h4>
<h4>第1次測試因為stick為可穿透的，所以ball沒辦法被stick擋住，還有程式控制鍵盤上下鍵所位移的位置和設定需再調整，第2次測試stick為不可穿透，但程式控制鍵盤上下有問題，所以還須修正</h4>
<p><img alt="" height="80" src="/images/0107.png" width="400"/></p>
<h4>程式</h4>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">-- model in Solvespace 500 mm = 5000 mm in V-rep
--[[
Simulation is 10 times of realistic environment
floor in Solvespace 2.5 m x 2.5 m = 25 m x 25 m in V-rep
ball is in Solivespace 1g (0.001) = 0.01 kg in V-rep
stick is in Solvespace 0.1 kg (100g) = 1kg in V-rep (0.1 for Inertia)
]]

threadFunction=function()
    while sim.getSimulationState()~=sim.simulation_advancing_abouttostop do
        -- Read the keyboard messages (make sure the focus is on the main window, scene view):
        message,auxiliaryData=sim.getSimulatorMessage()
        while message~=-1 do
            if (message==sim.message_keypress) then
                if (auxiliaryData[1]==2007) then
                    -- up key
                    velocity=50
                    stick_back = 0
                end
                if (auxiliaryData[1]==2008) then
                    -- down key
                     stick_back = 1
                     velocity = -50
                end
            end
            message,auxiliaryData=sim.getSimulatorMessage()
        end
 
        -- We take care of setting the desired stick position:
        if stick_back == 1
            then sim.setObjectPosition(stick,-1, position)
        end
        sim.setJointTargetVelocity(joint,velocity)
 
        -- Since this script is threaded, don't waste time here:
        sim.switchThread() -- Resume the script at next simulation loop start
    end
end
-- Put some initialization code here:
-- Retrieving of some handles and setting of some initial values:
joint=sim.getObjectHandle('joint')
stick=sim.getObjectHandle('stick')
velocity=0
stick_back=0
position=sim.getObjectPosition(stick,-1)
 
-- Here we execute the regular thread code:
res,err=xpcall(threadFunction,function(err) return debug.traceback(err) end)
if not res then
    sim.addStatusbarMessage('Lua runtime error: '..err)
end
 
-- Put some clean-up code here:</pre>
<p></p>
<h3>01-15</h3>
<h4>測試影片</h4>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/o9oK-7f_33U" width="560"></iframe></p>
<h4><a href="/downloads/彈珠台/pinblall-17.ttt">pinblall-17.ttt</a></h4>
<h4><a href="/downloads/彈珠台/彈珠檯-888.stl">圖檔</a></h4>
<h4>將之前的桿子改成圓桿，球和桿子能確實地做動，但還是有破圖、球卡到角飛出去、桿子座標亂飄等問題尚未解決。</h4>
<h4>程式</h4>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">-- model in Solvespace 500 mm = 5000 mm in V-rep
--[[
Simulation is 10 times of realistic environment
floor in Solvespace 2.5 m x 2.5 m = 25 m x 25 m in V-rep
ball is in Solivespace 1g (0.001) = 0.01 kg in V-rep
Cylinder is in Solvespace 0.1 kg (100g) = 1kg in V-rep (0.1 for Inertia)
]]

threadFunction=function()
    while sim.getSimulationState()~=sim.simulation_advancing_abouttostop do
        -- Read the keyboard messages (make sure the focus is on the main window, scene view):
        message,auxiliaryData=sim.getSimulatorMessage()
        while message~=-1 do
            if (message==sim.message_keypress) then
                if (auxiliaryData[1]==2007) then
                    -- up key
                    velocity=0.5
                    Cylinder_back = 0
                end
                if (auxiliaryData[1]==2008) then
                    -- down key
                     Cylinder_back = 1
                     velocity = -0.5
                end
            end
            message,auxiliaryData=sim.getSimulatorMessage()
        end
 
        -- We take care of setting the desired Cylinder position:
        if Cylinder_back == 1
            then sim.setObjectPosition(Cylinder,-1, position)
        end
        sim.setJointTargetVelocity(joint,velocity)
 
        -- Since this script is threaded, don't waste time here:
        sim.switchThread() -- Resume the script at next simulation loop start
    end
end
-- Put some initialization code here:
-- Retrieving of some handles and setting of some initial values:
joint=sim.getObjectHandle('joint')
Cylinder=sim.getObjectHandle('Cylinder')
velocity=0
Cylinder_back=0
position=sim.getObjectPosition(Cylinder,-1)
 
-- Here we execute the regular thread code:
res,err=xpcall(threadFunction,function(err) return debug.traceback(err) end)
if not res then
    sim.addStatusbarMessage('Lua runtime error: '..err)
end
 
-- Put some clean-up code here:</pre>
<p></p>
<h1>筆記</h1>
<h4>一、開啟9443</h4>
<p><img alt="" height="276" src="/images/9443.PNG" width="978"/></p>
<p>先打指令到cmsimde資料夾</p>
<p>在執行python wsgi.py指令</p>
<p>網址搜尋https://localhost:9443/</p>
<p>或複製黑窗最後一行的網址</p>
<p><img alt="" height="274" src="/images/9443-1.png" width="978"/></p>
<p>案login登入→密碼admin</p>
<h4>二、開啟8444</h4>
<p>先到scad2資料夾找到http-server.py檔案</p>
<p><img alt="" height="591" src="/images/8444.PNG" width="680"/></p>
<p>使用白窗開啟http-server.py</p>
<p>點選Tools→go</p>
<p><img alt="" height="445" src="/images/8444-1.PNG" width="560"/></p>
<h4>三、製作金鑰</h4>
<p>點選資料夾的Portablegit<span>→bin→sh.exe</span></p>
<p><span><img alt="" height="510" src="/images/ssh-11.PNG" width="976"/></span></p>
<h6>輸入ssh-keygen -t rsa -b 4096 -C "40823245"</h6>
<p><span style="color: #ff0000;">請自行改成自己的學號</span></p>
<p>案enter<span>→輸入/y/tmp/id_rsa→案2次enter</span></p>
<p><span><img alt="" height="401" src="/images/ssh-12.PNG" width="630"/></span></p>
<p>下載<a href="/downloads/putty.zip">putty</a>、<a href="/downloads/putty_home.zip">putty_home</a>、<a href="/downloads/GitExtensions.zip">GitExtensions</a><span style="color: #ff0000;">(請自行更改路徑)</span></p>
<p>將start移到白窗  並新增 </p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">set GIT_HOME=%Disk%:\Portablegit\bin\
set GIT_SSH=%Disk%:\putty\plink.exe</pre>
<p></p>
<p><img alt="" height="729" src="/images/ssh-13.PNG" width="563"/></p>
<p>打開.git資料夾，把config移到白窗</p>
<p>如沒有.git資料夾 打開隱藏的項目</p>
<p><img alt="" height="349" src="/images/ssh-14.PNG" width="1191"/></p>
<p>新增<span>[remote "origin"]裡的</span>url = git@github.com:40823245/cad2020.git</p>
<p><img alt="" height="444" src="/images/ssh.PNG" width="562"/></p>
<p><span>file→save</span></p>
<p><span>打開putty資料夾的puttygen.exe</span></p>
<p><span>點load，找到id_rsa</span></p>
<p><span><img alt="" height="523" src="/images/ssh-15.PNG" width="789"/></span></p>
<p><span>案是→Save private key→案是→輸入學號(存.ppk檔)</span></p>
<p><span>打開putty.exe</span></p>
<p><span><img alt="" height="441" src="/images/ssh-16.PNG" width="454"/></span></p>
<p><span></span>若沒有github.com，在Host Name和Save Sessions打<span>github.com案Save</span></p>
<p><span><img alt="" height="442" src="/images/ssh-19.png" width="452"/></span></p>
<p>設定proxy(使用自家網路、手機網路請選None)</p>
<p>看你的網路連到哪一台 就打一樣的proxy</p>
<p><img alt="" height="442" src="/images/ssh-20.png" width="452"/></p>
<p>打開SSH裡面的Auth</p>
<p>選擇你所生產的金鑰檔案(.ppk)</p>
<p>回到session點選save再open</p>
<p><img alt="" height="420" src="/images/ssh-1.PNG" width="667"/></p>
<p>在home新增.ssh資料夾</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">ProxyCommand y:/putty/plink.exe github.com %h %p
 
Host github.com
    User git
    Port 22
    Hostname github.com
 
    TCPKeepAlive yes
    IdentitiesOnly yes

</pre>
<p></p>
<p>將上面的指令複製到白窗並另存config</p>
<p>到倉儲網頁新增金鑰(右上Settings)</p>
<p><img alt="" height="494" src="/images/ssh-17.PNG" width="1011"/></p>
<p>點New SSH key</p>
<p>到tmp找到id_rsa.pub並用白窗開啟，複製內容到Key</p>
<p>並確認學號</p>
<p><img alt="" height="434" src="/images/ssh-18.PNG" width="1040"/></p>
<p></p>
<p>案Add SSH key</p>
<h4>四、進行上傳</h4>
<h5>方法一</h5>
<p>先進到scad2  → cd tmp/scad2</p>
<p>git add .</p>
<p>git commit -m "此更新的主旨"</p>
<p>git push</p>
<p>輸入帳號(學號)</p>
<p>輸入密碼</p>
<h5>方法二(啟用ssh)</h5>
<p>要先改.git裡面的config</p>
<p>[remote "origin"]把之前的https加上#</p>
<p><img alt="" height="444" src="/images/ssh.PNG" width="562"/></p>
<p>開啟putty(putty.exe)   將設定調好</p>
<p>點github.com  案load</p>
<p>設定proxy(使用自家網路、手機網路請選None)</p>
<p>看你的網路連到哪一台 就打一樣的proxy</p>
<p>打開SSH裡面的Auth</p>
<p>選擇你所生產的金鑰檔案(.ppk)</p>
<p>回到session點選save再open</p>
<p><img alt="" height="420" src="/images/ssh-1.PNG" width="667"/></p>
<p>出現上圖就代表成功</p>
<p>一樣先進到scad2  → cd tmp/scad2</p>
<p>git add .</p>
<p>git commit -m "此更新的主旨"</p>
<p>git push</p>
<p>(此方法不需打帳號密碼)</p>
<h5>方法三(啟用ssh)</h5>
<p>使用資料夾的GitExtensions</p>
<p>點選GitExtensions.exe</p>
<p>修改設定</p>
<p><img alt="" height="777" src="/images/ssh-2.PNG" width="958"/></p>
<p><img alt="" height="779" src="/images/ssh-3.PNG" width="960"/></p>
<p>確認正確以後   點OK</p>
<p>選擇Create new repository</p>
<p><img alt="" height="607" src="/images/ssh-4.PNG" width="925"/></p>
<p>brown找到scad2資料夾後點Create</p>
<p>點tools→Git GUI</p>
<p><img alt="" height="485" src="/images/ssh-5.PNG" width="841"/></p>
<p><span>先點Stage Changed(=git add .)</span></p>
<p><span><img alt="" height="485" src="/images/ssh-6.PNG" width="833"/></span></p>
<p><span>案是</span></p>
<p><span><img alt="" height="484" src="/images/ssh-7.PNG" width="834"/></span></p>
<p><span>案Continue</span></p>
<p><span><img alt="" height="486" src="/images/ssh-8.PNG" width="836"/></span></p>
<p>左下的框會出現資料</p>
<p>然後右下的位置打上這次變更的主旨(=<span>git commit -m "此更新的主旨"</span>)可輸入中文</p>
<p><img alt="" height="485" src="/images/ssh-9.PNG" width="839"/></p>
<p>點Commit→Push<span>→Push</span></p>
<p><span><img alt="" height="269" src="/images/ssh-10.PNG" width="593"/></span></p>
<h4>五、修改網頁標題</h4>
<p>打開資料夾找到init.py</p>
<p><img alt="" height="661" src="/images/init-1.PNG" width="778"/></p>
<p><span>使用白窗打開</span></p>
<p><img alt="" height="731" src="/images/init.PNG" width="560"/></p>
<p>找到並修改成site_title = "學號 cad2020"</p>
<p>file→save就可完成</p>
<h4>六、Zoomit</h4>
<p>1、Ctrl+1:畫面放大+按下滑鼠進入畫畫模式(<span>ESC能解除</span>)</p>
<p>2、<span>Ctrl+2:進入畫畫模式(ESC能解除)</span></p>
<p><span>3、Ctrl+3:出現倒數的時間，休息時間剩多久(ESC能解除、Ctrl+3重置倒數時間)</span></p>
<p><span>4、<span>Ctrl+4:放大鏡(Ctrl+4<span>能解除)</span></span></span></p>
<p>5、畫畫模式:滑鼠直接畫任意線段、TAB+滑鼠滑動=畫圓、Shift+滑鼠滑動=畫直線</p>
<p>Ctrl+<span>滑鼠滑動=畫矩形、Shift+Ctrl+滑鼠滑動=畫指線、Ctrl+T=打字</span></p>
<h1>問題</h1>
<p>在倉儲github網站中，會發現少了downloads的資料夾</p>
<p><img alt="" height="350" src="/images/problem (1).png" width="179"/></p>
<p>需要做以下修改，並能解決問題</p>
<p>將scad2裡的.gitignore裡面的downloads/刪除，並save</p>
<p><img alt="" height="600" src="/images/problem.png" width="1000"/></p>
<p>重新push後github就能有downloads了</p>
<p><img alt="" height="350" src="/images/problem (2).png" width="161"/></p>
<p>原因:gitignore會幫你忽視以下的檔案，為了防止他人能clone到你的某些檔案</p>
<h1>心得</h1>
<h4>這學期的課程和之前不太一樣，比較偏向畫圖和設計模擬，對我來講又是新的課程，而且又被選為組長，要多多幫助組員解決問題，甚至其他同學也來問我，雖然不知我能否順利解決他們的問題，但經過一次又一次的錯誤嘗試和上網看其他人解決的辦法，使我更了解網頁設計。</h4>